### ISSUE TITLE
Need results on my dataset

### ISSUE THREAD

**Issue by darrayes** [shashiongithub/sidenet#1]
Hi,
I want to compare the results with my own system and hence I need help in two issues:

1. My dataset is the same CNN but the way labels are found is different. hence the dataset is essentially different.
2. I don't want to limit to three sentences in full length evalaution. 

Can you help me with these two issues and point to relevant sections of the code.

**Comment by shashiongithub** [comment]
1) My dataset is the same CNN but the way labels are found is different. hence the dataset is essentially different.

What labels are you talking about? Could you explain, I am not able to help with the provided information.

2) I  don't want to limit to three sentences in full length evalaution.

data_utils calls a funtion called: predict_toprankedthree from model_utils. You have to replace this function or change values in this function.

**Comment by darrayes** [comment]
I mean to say the way you label a sentence as being eligible for summary or not (0 or 1) is different for me.

**Comment by shashiongithub** [comment]
We treat it as a sequence labeling task using binary labels.
