### ISSUE TITLE
Doubt in getting pretrained word embeddings 

### ISSUE THREAD

**Issue by riddhirdasani** [shashiongithub/sidenet#2]
from where I can get this pretrained vectors?
 1. WordEmbeddings/cnn-dailymail_doc-highlights-title-image_Org.txt.word2vec.vec
 2.WordEmbeddings/cnn-dailymail_doc-highlights-title-image_Anonymized.txt.word2vec.vec

**Comment by shashiongithub** [comment]
Hi Riddhi, 
Please find our preprocessed input here. 
http://kinloch.inf.ed.ac.uk/public/sidenet-cnn-inputs.tar.gz
Hope this helps,
Shashi
